/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sndyuk' at '11/7/16 11:04 PM' with Gradle 3.1
 *
 * @author sndyuk, @date 11/7/16 11:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
